### ISSUE TITLE
getName повторный вызов

### ISSUE THREAD

**Issue by so2niko** [Daniil-Kudlach/HomeWorks#1]
https://github.com/Daniil-Kudlach/HomeWorks/blob/2d59779139bd84464b7822a976cfda1e9e8993b5/Chat_MVC/app/Chat/ControllerChat.js#L56

У вас уже есть переменная с этими данными. Не стоит опять вычитывать их из Вьюхи

**Comment by Daniil-Kudlach** [comment]
Спасибо за комментарий. Проект **изменён** согласно рекомендациям))
