### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by so2niko** [Daniil-Kudlach/HomeWorks#2]
https://github.com/Daniil-Kudlach/HomeWorks/blob/2d59779139bd84464b7822a976cfda1e9e8993b5/Chat_MVC/app/Chat/ViewChat.js#L32

_ParentNode.append() позволяет добавить несколько узлов (node) или строк, в то время как Node.appendChild() может добавть только один узел (node)._

https://github.com/Daniil-Kudlach/HomeWorks/blob/2d59779139bd84464b7822a976cfda1e9e8993b5/Chat_MVC/app/Chat/ViewChat.js#L25

Здесь и ниже шаблонные строки **не нужны.**

https://github.com/Daniil-Kudlach/HomeWorks/blob/2d59779139bd84464b7822a976cfda1e9e8993b5/Chat_MVC/app/Chat/ViewChat.js#L61

Это гетер. Стоит использовать приставку **get**

**Comment by Daniil-Kudlach** [comment]
Спасибо за развернутый комментарий, проект **изменён** с учетом рекомендаций))
